### ISSUE TITLE
Fix failing cloud tests

### ISSUE THREAD

**Issue by debanjum** [debanjum/semantic-search#11]
The Github Actions pipeline is failing because the pipeline is not able to find the sbert `model_name` for CLIP

![image](https://user-images.githubusercontent.com/6413477/144698802-c7c7fcfd-cbf8-45a5-bffd-4423832decb3.png)

**Comment by sabaimran** [comment]
After fixing `model_name` issue, see this issue for dev setup using `exiftool`:
`ERROR tests/test_image_search.py::test_image_search_setup - FileNotFoundError: [Errno 2] No such file or directory: 'exiftool'`

```
src/search_type/image_search.py:167: in setup
    image_embeddings, image_metadata_embeddings = compute_embeddings(
src/search_type/image_search.py:40: in compute_embeddings
    image_metadata_embeddings = compute_metadata_embeddings(image_names, encoder, embeddings_file, batch_size, use_xmp_metadata, regenerate, verbose)
src/search_type/image_search.py:80: in compute_metadata_embeddings
    image_metadata = [extract_metadata(image_name, verbose) for image_name in image_names[index:index+batch_size]]
src/search_type/image_search.py:80: in <listcomp>
    image_metadata = [extract_metadata(image_name, verbose) for image_name in image_names[index:index+batch_size]]
src/search_type/image_search.py:90: in extract_metadata
    with exiftool.ExifTool() as et:
src/utils/exiftool.py:191: in __enter__
    self.start()
src/utils/exiftool.py:170: in start
    self._process = subprocess.Popen(
../../miniconda3/envs/semantic-search/lib/python3.9/subprocess.py:951: in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
```

**Comment by sabaimran** [comment]
Now just seeing one issue:
`FAILED tests/test_client.py::test_image_search - AssertionError: assert PosixPath('.../tests/data/kitten_park.jpg') == PosixPath('.../tests/data/guineapig_grass.jpg/)`

Not sure what to do about this one 🥲 .

**Comment by debanjum** [comment]
Skipping the flaky client test for image search for now to allow cloud build to pass
